apiVersion: v1
kind: Service
metadata:
  name: apm-golang
  labels:
    app: apm-golang
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: apm-golang
